// Auto-NPU .npug ABI v0.1 — generated by cbindgen. DO NOT EDIT.

#ifndef NPUG_H
#define NPUG_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define npug_ENUM_MIN_ABI_VERSION 0

#define npug_ENUM_MAX_ABI_VERSION 256

#define npug_ENUM_MIN_TARGET_ID 0

#define npug_ENUM_MAX_TARGET_ID 1

#define npug_ENUM_MIN_DTYPE 0

#define npug_ENUM_MAX_DTYPE 14

#define npug_ENUM_MIN_QUANT_SCHEME 0

#define npug_ENUM_MAX_QUANT_SCHEME 4

#define npug_ENUM_MIN_MEMORY_REGION 0

#define npug_ENUM_MAX_MEMORY_REGION 4

#define npug_ENUM_MIN_KERNEL_KIND 0

#define npug_ENUM_MAX_KERNEL_KIND 2

#define npug_CURRENT 256

#define npug_Shape_VT_DIMS 4

#define npug_Shape_VT_SYMBOL_NAMES 6

#define npug_Buffer_VT_DATA 4

#define npug_QuantInfo_VT_SCHEME 4

#define npug_QuantInfo_VT_SCALE_BUFFER 6

#define npug_QuantInfo_VT_ZERO_POINT_BUFFER 8

#define npug_QuantInfo_VT_AXIS 10

#define npug_QuantInfo_VT_BLOCK_SIZE 12

#define npug_Tensor_VT_NAME 4

#define npug_Tensor_VT_DTYPE 6

#define npug_Tensor_VT_SHAPE 8

#define npug_Tensor_VT_BUFFER 10

#define npug_Tensor_VT_QUANT 12

#define npug_Tensor_VT_REGION 14

#define npug_Tensor_VT_OFFSET 16

#define npug_Kernel_VT_KIND 6

#define npug_Kernel_VT_ENTRY_OFFSET 10

#define npug_Graph_VT_ABI_VERSION 4

#define npug_Graph_VT_TARGET 6

#define npug_Graph_VT_PRODUCER 8

#define npug_Graph_VT_TENSORS 10

#define npug_Graph_VT_BUFFERS 12

#define npug_Graph_VT_KERNELS 14

#define npug_Graph_VT_ENTRY_POINTS 16

#define npug_ScheduleEntry_VT_TILE_ID 4

#define npug_ScheduleEntry_VT_KERNEL_INDEX 6

#define npug_ScheduleEntry_VT_ARGS_OFFSET 8

#define npug_ScheduleEntry_VT_ARGS_SIZE 10

#define npug_Bucket_VT_SHAPE_HINT 4

#define npug_Bucket_VT_SCHEDULE 6

#define npug_EntryPoint_VT_INPUTS 6

#define npug_EntryPoint_VT_OUTPUTS 8

#define npug_EntryPoint_VT_BUCKETS 10

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the crate's ABI version (e.g. 0x000100).
 */
uint32_t npug_abi_version(void);

/**
 * Returns 1 if `bytes[..len]` parses as a valid .npug with compatible ABI, else 0.
 *
 * # Safety
 * `bytes` must be valid for reads of `len` bytes.
 */
int32_t npug_validate(const uint8_t *bytes, uintptr_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NPUG_H */
