// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod npug {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ABI_VERSION: u32 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ABI_VERSION: u32 = 256;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ABI_VERSION: [AbiVersion; 2] = [
  AbiVersion::Unknown,
  AbiVersion::V0_1_0,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct AbiVersion(pub u32);
#[allow(non_upper_case_globals)]
impl AbiVersion {
  pub const Unknown: Self = Self(0);
  pub const V0_1_0: Self = Self(256);

  pub const ENUM_MIN: u32 = 0;
  pub const ENUM_MAX: u32 = 256;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Unknown,
    Self::V0_1_0,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Unknown => Some("Unknown"),
      Self::V0_1_0 => Some("V0_1_0"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for AbiVersion {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for AbiVersion {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u32>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for AbiVersion {
    type Output = AbiVersion;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u32>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for AbiVersion {
  type Scalar = u32;
  #[inline]
  fn to_little_endian(self) -> u32 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u32) -> Self {
    let b = u32::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for AbiVersion {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u32::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for AbiVersion {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_TARGET_ID: u32 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_TARGET_ID: u32 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_TARGET_ID: [TargetId; 2] = [
  TargetId::Unknown,
  TargetId::AutoSocV1,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct TargetId(pub u32);
#[allow(non_upper_case_globals)]
impl TargetId {
  pub const Unknown: Self = Self(0);
  pub const AutoSocV1: Self = Self(1);

  pub const ENUM_MIN: u32 = 0;
  pub const ENUM_MAX: u32 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Unknown,
    Self::AutoSocV1,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Unknown => Some("Unknown"),
      Self::AutoSocV1 => Some("AutoSocV1"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for TargetId {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for TargetId {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u32>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for TargetId {
    type Output = TargetId;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u32>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for TargetId {
  type Scalar = u32;
  #[inline]
  fn to_little_endian(self) -> u32 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u32) -> Self {
    let b = u32::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for TargetId {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u32::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for TargetId {}
pub enum GraphOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Graph<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Graph<'a> {
  type Inner = Graph<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Graph<'a> {
  pub const VT_ABI_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_TARGET: ::flatbuffers::VOffsetT = 6;
  pub const VT_PRODUCER: ::flatbuffers::VOffsetT = 8;
  pub const VT_ENTRY_POINTS: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Graph { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GraphArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Graph<'bldr>> {
    let mut builder = GraphBuilder::new(_fbb);
    if let Some(x) = args.entry_points { builder.add_entry_points(x); }
    if let Some(x) = args.producer { builder.add_producer(x); }
    builder.add_target(args.target);
    builder.add_abi_version(args.abi_version);
    builder.finish()
  }

  pub fn unpack(&self) -> GraphT {
    let abi_version = self.abi_version();
    let target = self.target();
    let producer = self.producer().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let entry_points = self.entry_points().map(|x| {
      x.iter().map(|t| t.unpack()).collect()
    });
    GraphT {
      abi_version,
      target,
      producer,
      entry_points,
    }
  }

  #[inline]
  pub fn abi_version(&self) -> AbiVersion {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<AbiVersion>(Graph::VT_ABI_VERSION, Some(AbiVersion::Unknown)).unwrap()}
  }
  #[inline]
  pub fn target(&self) -> TargetId {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<TargetId>(Graph::VT_TARGET, Some(TargetId::Unknown)).unwrap()}
  }
  #[inline]
  pub fn producer(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Graph::VT_PRODUCER, None)}
  }
  #[inline]
  pub fn entry_points(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<EntryPoint<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<EntryPoint>>>>(Graph::VT_ENTRY_POINTS, None)}
  }
}

impl ::flatbuffers::Verifiable for Graph<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<AbiVersion>("abi_version", Self::VT_ABI_VERSION, false)?
     .visit_field::<TargetId>("target", Self::VT_TARGET, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("producer", Self::VT_PRODUCER, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<EntryPoint>>>>("entry_points", Self::VT_ENTRY_POINTS, false)?
     .finish();
    Ok(())
  }
}
pub struct GraphArgs<'a> {
    pub abi_version: AbiVersion,
    pub target: TargetId,
    pub producer: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub entry_points: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<EntryPoint<'a>>>>>,
}
impl<'a> Default for GraphArgs<'a> {
  #[inline]
  fn default() -> Self {
    GraphArgs {
      abi_version: AbiVersion::Unknown,
      target: TargetId::Unknown,
      producer: None,
      entry_points: None,
    }
  }
}

pub struct GraphBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GraphBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_abi_version(&mut self, abi_version: AbiVersion) {
    self.fbb_.push_slot::<AbiVersion>(Graph::VT_ABI_VERSION, abi_version, AbiVersion::Unknown);
  }
  #[inline]
  pub fn add_target(&mut self, target: TargetId) {
    self.fbb_.push_slot::<TargetId>(Graph::VT_TARGET, target, TargetId::Unknown);
  }
  #[inline]
  pub fn add_producer(&mut self, producer: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Graph::VT_PRODUCER, producer);
  }
  #[inline]
  pub fn add_entry_points(&mut self, entry_points: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<EntryPoint<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Graph::VT_ENTRY_POINTS, entry_points);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GraphBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GraphBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Graph<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Graph<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Graph");
      ds.field("abi_version", &self.abi_version());
      ds.field("target", &self.target());
      ds.field("producer", &self.producer());
      ds.field("entry_points", &self.entry_points());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct GraphT {
  pub abi_version: AbiVersion,
  pub target: TargetId,
  pub producer: Option<alloc::string::String>,
  pub entry_points: Option<alloc::vec::Vec<EntryPointT>>,
}
impl Default for GraphT {
  fn default() -> Self {
    Self {
      abi_version: AbiVersion::Unknown,
      target: TargetId::Unknown,
      producer: None,
      entry_points: None,
    }
  }
}
impl GraphT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<Graph<'b>> {
    let abi_version = self.abi_version;
    let target = self.target;
    let producer = self.producer.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let entry_points = self.entry_points.as_ref().map(|x|{
      let w: alloc::vec::Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();_fbb.create_vector(&w)
    });
    Graph::create(_fbb, &GraphArgs{
      abi_version,
      target,
      producer,
      entry_points,
    })
  }
}
pub enum EntryPointOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EntryPoint<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for EntryPoint<'a> {
  type Inner = EntryPoint<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> EntryPoint<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    EntryPoint { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EntryPointArgs<'args>
  ) -> ::flatbuffers::WIPOffset<EntryPoint<'bldr>> {
    let mut builder = EntryPointBuilder::new(_fbb);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> EntryPointT {
    let name = self.name().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    EntryPointT {
      name,
    }
  }

  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(EntryPoint::VT_NAME, None)}
  }
}

impl ::flatbuffers::Verifiable for EntryPoint<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .finish();
    Ok(())
  }
}
pub struct EntryPointArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for EntryPointArgs<'a> {
  #[inline]
  fn default() -> Self {
    EntryPointArgs {
      name: None,
    }
  }
}

pub struct EntryPointBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EntryPointBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EntryPoint::VT_NAME, name);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> EntryPointBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EntryPointBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<EntryPoint<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for EntryPoint<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("EntryPoint");
      ds.field("name", &self.name());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct EntryPointT {
  pub name: Option<alloc::string::String>,
}
impl Default for EntryPointT {
  fn default() -> Self {
    Self {
      name: None,
    }
  }
}
impl EntryPointT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<EntryPoint<'b>> {
    let name = self.name.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    EntryPoint::create(_fbb, &EntryPointArgs{
      name,
    })
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Graph`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_graph_unchecked`.
pub fn root_as_graph(buf: &[u8]) -> Result<Graph<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Graph>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Graph` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_graph_unchecked`.
pub fn size_prefixed_root_as_graph(buf: &[u8]) -> Result<Graph<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Graph>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Graph` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_graph_unchecked`.
pub fn root_as_graph_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Graph<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Graph<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Graph` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_graph_unchecked`.
pub fn size_prefixed_root_as_graph_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Graph<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Graph<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Graph and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Graph`.
pub unsafe fn root_as_graph_unchecked(buf: &[u8]) -> Graph<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Graph>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Graph and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Graph`.
pub unsafe fn size_prefixed_root_as_graph_unchecked(buf: &[u8]) -> Graph<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Graph>(buf) }
}
pub const GRAPH_IDENTIFIER: &str = "NPUG";

#[inline]
pub fn graph_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, GRAPH_IDENTIFIER, false)
}

#[inline]
pub fn graph_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, GRAPH_IDENTIFIER, true)
}

pub const GRAPH_EXTENSION: &str = "npug";

#[inline]
pub fn finish_graph_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Graph<'a>>) {
  fbb.finish(root, Some(GRAPH_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_graph_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Graph<'a>>) {
  fbb.finish_size_prefixed(root, Some(GRAPH_IDENTIFIER));
}
}  // pub mod Npug

